### PR TITLE
Changed required package version (for 10.13.1)

### PR DESCRIPTION
**Pull request by huntrax11**
Changed the version of package dependencies.
I found this patch works fine with mac os 10.13.1.

### CODE REVIEW

**Comment by liangtb** [comment]
@huntrax11 HOW work FINE???


@pedroresende @yifanlu 
Have several issues with mac os 10.13.1 on macbook pro retina 15 with gt750m

ISSUE 1:

The V2 version on 10.13.1 makes screen brightness adjustment disable and automate adjustment nonfunctional.

ISSUE 2:

The automate gpu switch is disabled and set Nvidia-GPU as default.

ISSUE 3：

After a little long cover sleep, it can not be awaked from sleeping. GOT BLACK SCREEN.

**Comment by pedroresende** [comment]
@liangtb The changes proposed by @yifanlu are only related with nvidia's drivers. Remember that this tool is a **hack** to allow you to use a hardware device that shouldn't work

**Comment by liangtb** [comment]
@pedroresende I just said something about this script's issue and you feel arrogant and cranky.

**Comment by huntrax11** [comment]
@pedroresende I think he doesn't deserve a comment.

FYI.
- https://github.com/mayankk2308/purge-nvda/issues/5
- https://github.com/Jire/Overwatcheat/issues/44#issuecomment-338491876

**Comment by liangtb** [comment]
@Hunchul Park you forked other script and said it worked fine
irresponsibly. I just questioned about this. Look your reaction! What a
sham on you!

On 5 November 2017 at 8:04:36 PM, Hunchul Park (notifications@github.com)
wrote:

@pedroresende <https://github.com/pedroresende> I think he doesn't deserve
a comment.

FYI.

   - mayankk2308/purge-nvda#5
   <https://github.com/mayankk2308/purge-nvda/issues/5>
   - Jire/Overwatcheat#44 (comment)
   <https://github.com/Jire/Overwatcheat/issues/44#issuecomment-338491876>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pedroresende/NVIDIAEGPUSupport/pull/1#issuecomment-341968141>,
or mute the thread

**Comment by huntrax11** [comment]
@liangtb You did say it to me like below.

> @huntrax11 HOW work FINE???

> @Hunchul Park you forked other script and said it worked fine irresponsibly.
> I just questioned about this. Look your reaction! What a sham on you!

While you point out that I was irresponsible to say "works fine", there is at least 10+ posts confirming this patch is working since [devild's build containing this patch][egpu-forum].
Your issue is irrelevant to this pull request.
Don't tell me that I'm irresponsible because of the irrelevant issue.


Second, They, who you mentioned, just serve the open source community, not you.
No one has any obligation to help your technical difficulties.
(If you don't get it, please refer the [LICENSE][license])

Finally, How dare you saying "arrogant and cranky" to the maintainer.
I can't find any respect for the community from you.

[egpu-forum]:https://egpu.io/forums/mac-setup/wip-nvidia-egpu-support-for-high-sierra/paged/12/#post-23267
[license]:https://github.com/pedroresende/NVIDIAEGPUSupport/blob/master/LICENSE#L17

**Comment by pedroresende** [comment]
@liangtb The patch works, I'm using it with my setup (Mac Mini 2012, Akitio Thunderbold 2 and Nvidia 750TI). On my setup it works pretty fine

**Pull request merged**
